services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgresDB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
